import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "sonner";
import { QueryClientProvider } from "@tanstack/react-query";
import ReactQueryProvider from "@/providers/react-query-provider";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
    <body 
    suppressHydrationWarning
    className={jakarta.className}>
    <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            disableTransitionOnChange
          >
           <ReactQueryProvider>{children}</ReactQueryProvider>
            <Toaster/>
      </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
  
}
